version: '3'

services:

  crypto:
    build:
      context: ./crypto
    image: ivonet/crypto
    ports:
      - 5000:5000
    environment:
      - DEBUG=0

  crypto-fe:
    build:
      context: ./crypto-fe
    image: ivonet/crypto-fe
    ports:
      - 8080:80
    depends_on:
      - crypto
    links:
      - crypto

