#!/usr/bin/env python
#  -*- coding: utf-8 -*-

GAMES = {"A": [
    ("Abalone", "Bordspel"),
    ("Adel verplicht", "Bordspel"),
    ("Afrika", "Bordspel"),
    ("Alhambra", "Bordspel"),
    ("Alquerque", "Bordspel"),
    ("Amazone", "Bordspel"),
    ("Amon Ra", "Bordspel"),
    ("Andromeda", "Bordspel"),
    ("Asalto", "Bordspel"),
    ("Athos", "Bordspel"),
    ("Attika", "Bordspel"),
    ("Arriba", "Kaartspel (beter bekend als Jungle Speed)"),
    ("Ave Caesar", "Bordspel"),
    ("Axis & Allies", "Bordspel"),
], "B": [
    ("Babel", "Bordspel"),
    ("Backgammon", "Bordspel"),
    ("Bang", "Kaartspel"),
    ("Barricade", "Bordspel"),
    ("Bedriegers Bedrogen", "Kaartspel"),
    ("De Beer Is Los", "Bordspel"),
    ("De betoverde doolhof", "Bordspel"),
    ("Big City", "Bordspel"),
    ("Bikkelen", "Straat- en pleinspel"),
    ("Blackjack", "Kaartspel"),
    ("Blokus", "Bordspel"),
    ("Blue Moon", "Bordspel"),
    ("Blufpoker", "Dobbelspel"),
    ("Boem", "gezelschapsspel"),
    ("Boerenbridge", "Kaartspel"),
    ("Boggle", "Puzzelspel"),
    ("Boonanza", "Kaartspel"),
    ("Bonken", "Kaartspel"),
    ("Boonanza (Nederlandstalige versie van Bohnanza)", "Kaartspel"),
    ("Bridge", "Kaartspel"),
    ("De Bruggen van Shangrila", "Bordspel"),
], "C": [
    ("Canasta", "Kaartspel"),
    ("Carcassonne", "Bordspel"),
    ("Caroms", "Bordspel"),
    ("Castello", "Bordspel"),
    ("Cartagena", "Bordspel"),
    ("Charlemagne", "Bordspel"),
    ("Chez Geek", "Kaartspel"),
    ("De Chinese Muur", "Kaartspel"),
    ("CIA", "Bordspel"),
    ("Clans", "Bordspel"),
    ("Cluedo", "Bordspel"),
    ("Commando pinkelen", ""),
    ("Conkers", "Straat- en pleinspel"),
    ("Cranium", "Bordspel"),
], "D": [
    ("Dammen", "Bordspel"),
    ("Diplomacy", "Bordspel"),
    ("Dominion", "Kaartspel"),
    ("Domino", "Puzzelspel"),
    ("Duizend kilometer", "Kaartspel"),
    ("Duizenden", "Kaartspel"),
], "E": [
    ("Eenendertigen", "Kaartspel"),
    ("Eenentwintigen", "Kaartspel, zie blackjack"),
    ("El Grande", "Bordspel"),
    ("Eufraat & Tigris", "Bordspel"),
    ("Expedition", "Bordspel"),
    ("Ezelen", "Kaartspel"),
    ("Ezeltje strek je", "gezelschapsspel"),
], "F": [
    ("Fanorona", "Bordspel"),
    ("Forum Romanum", "Bordspel"),
], "G": [
    ("Ganzenbord", "Bordspel"),
    ("Genius", "Bordspel"),
    ("Gloom", "Kaartspel"),
    ("Go", "Bordspel"),
    ("Goa", "Bordspel"),
    ("Go-bang", "Bordspel"),
    ("De Grote Dalmuti", "Kaartspel"),
], "H": [
    ("Haas en Schildpad", "Bordspel"),
    ("Halli Galli", "Kaartspel"),
    ("Halma", "Bordspel"),
    ("Hartenjagen", "Kaartspel"),
    ("Heroquest", "Bordspel / Rollenspel"),
    ("Hinkelen", "Straat- en pleinspel"),
    ("Hoepelen", "Straat- en pleinspel"),
], "I": [
    ("Iguazu", "Bordspel"),
    ("In de ban van de ring", "Bordspel"),
], "J": [
    ("Jakkiebak! Kippenkak!", "Bordspel"),
    ("Jenga", "Evenwichtsspel"),
    ("Jeu de boules", "Straat- en pleinspel"),
    ("Jokeren", "Kaartspel"),
    ("Jungle Speed", "Kaartspel"),
], "K": [
    ("Kakuro Challenge", "Bordspel"),
    ("Kardinaal en Koning", "Bordspel"),
    ("Keezen", "Bordspel"),
    ("Keltis", "Bordspel"),
    ("Kiekeboe", "Straat- en pleinspel"),
    ("Killer Bunnies", "Kaartspel"),
    ("Kinder Bunnies", "Kaartspel"),
    ("De Klauter Kabouters", "Evenwichtsspel"),
    ("Klaverjassen", "Kaartspel"),
    ("Kleurensalada", "Evenwichtsspel"),
    ("Knikkeren", "Straat- en pleinspel"),
    ("Koehandel", "Kaartspel"),
    ("De Kolonisten van Catan", "Bordspel"),
    ("Koningsspel van Ur", "Bordspel"),
    ("Kubb", "straat- en pleinspel"),
    ("Kwartet", "Kaartspel"),
], "L": [
    ("Leeuwenhart", "Bordspel"),
    ("LETRZ", "Bordspel"),
    ("Levensweg", "Bordspel"),
    ("Lifestyle", "Bordspel"),
    ("Ligretto", "Kaartspel"),
    ("Lost Cities", "Kaartspel"),
    ("Lunar lockout", "Puzzelspel"),
    ("Luxor", "Bordspel"),
], "M": [
    ("Machiavelli", "Kaartspel"),
    ("Mad", "Bordspel"),
    ("Magic: [ The Gathering", "Kaartspel"),
    ("Mamma Mia", "Kaartspel"),
    ("Manilla", "Bordspel"),
    ("Mastermind", "Bordspel"),
    ("Medina", "Bordspel"),
    ("Meer of minder", "Kaartspel"),
    ("Memory", "Puzzelspel"),
    ("Mens erger je niet!", "Bordspel"),
    ("Mikado", "Evenwichtsspel"),
    ("Molenspel", "Bordspel"),
    ("Mollenmania", "Bordspel"),
    ("Monopoly", "Bordspel"),
    ("Munchkin", "Kaartspel"),
], "N": [
    ("Nautilus", "Bordspel"),
], "O": [
    ("Oh hell", "Kaartspel"),
    ("Once Upon A Time", "Kaartspel"),
    ("Onderuit", "Bordspel"),
    ("Ongelukslaan 13", "Bordspel"),
    ("Oog Des Meesters", "Rollenspel"),
    ("OXO", "spel"),
], "P": [
    ("Pachisi", "Bordspel"),
    ("Packhuys", "Bordspel"),
    ("Pandemie", "Bordspel"),
    ("Pandoeren", "Kaartspel"),
    ("Partner Link", "Erotisch spel"),
    ("Pentago", "Bordspel"),
    ("Perudo", "Dobbelspel"),
    ("Pesten", "Kaartspel"),
    ("Pim-pam-pet", "Puzzelspel"),
    ("Pisa", "Evenwichtspel"),
    ("Pluimbal", "Straat- en pleinspel"),
    ("Poch", "Bordspel"),
    ("Poker", "Kaartspel"),
    ("Pueblo (spel)", "Bordspel"),
    ("Puerto Rico", "Bordspel"),
    ("Pylos", "Bordspel"),
], "Q": [
    ("Quarto", "Bordspel"),
    ("Quoridor", "Bordspel"),
    ("Qwirkle", "Puzzelspel"),
], "R": [
    ("Ra", "Bordspel"),
    ("Ramses", "Bordspel"),
    ("Regenboogslang", "Kaartspel"),
    ("Regenwormen", "Dobbelspel"),
    ("Een Reis door Europa", "Bordspel"),
    ("Rikken", "Kaartspel"),
    ("Risk", "Bordspel, Dobbelspel"),
    ("River Crossing", "Puzzelspel"),
    ("Robo Rally", "Bordspel"),
    ("Rolit (ook bekend als Reversi)", "Bordspel"),
    ("Roll over", "Evenwichtsspel"),
    ("Rubiks kubus", "Eenpersoonsspel"),
    ("Rummikub", "Puzzelspel"),
    ("Rumba", "Kaartspel"),
    ("Rush Hour", "Eenpersoonsspel"),
], "S": [
    ("Saboteur", "Kaartspel"),
    ("Samurai", "Bordspel"),
    ("Schaken", "Bordspel"),
    ("Scotland Yard", "Bordspel"),
    ("Scrabble", "Bordspel"),
    ("Senet", "Bordspel"),
    ("Set!", "Kaartspel"),
    ("Shove Ha'penny", "Bordspel"),
    ("Sint Petersburg", "Bordspel"),
    ("Sky High!", "Bordspel"),
    ("Sky Runner", "Bordspel"),
    ("Slangen en ladders (ook wel ladderspel genoemd)", "Bordspel"),
    ("6nimmt", "Kaartspel"),
    ("Solitaire", "Eenpersoonsspel"),
    ("Sphinx", "Bordspel"),
    ("Spots", "Kaartspel"),
    ("Stef Stuntpiloot", "Evenwichtsspel"),
    ("Stixx", "Bordspel"),
    ("Stratego", "Bordspel"),
    ("Stroomopwaarts", "Bordspel"),
], "T": [
    ("Tafelhockey", "Bordspel"),
    ("Tai Pan", "Kaartspel"),
    ("Take 5! (Nederlandse versie van 6nimmt", "Kaartspel"),
    ("Take It Easy", "Puzzelspel"),
    ("Tangram", "Eenpersoonsspel"),
    ("Tantrix", "Puzzelspel"),
    ("Tayu", "Bordspel"),
    ("Terra Turium", "Bordspel"),
    ("Ticket to Ride", "Bordspel"),
    ("Tikal", "Bordspel"),
    ("Tlachtli", "Straat- en pleinspel"),
    ("Toepen", "Kaartspel"),
    ("Tollen", "Straat- en pleinspel"),
    ("Top Dop", "Evenwichtspel"),
    ("Touwtjespringen", "Straat- en pleinspel"),
    ("Transsport", "Bordspel"),
    ("Triominos", "Puzzelspel"),
    ("Triviant", "Bordspel"),
    ("Trivial Pursuit", "Bordspel"),
    ("Twister", "Straat- en pleinspel"),
], "U": [
    ("UNO", "Kaartspel"),
], "V": [
    ("Valkuil", "Bordspel"),
    ("Veel Soeps!", "Kaartspel"),
    ("Vier op 'n rij", "Bordspel"),
    ("Viersprong", "Bordspel"),
    ("Vijfhonderden", "Kaartspel"),
    ("Vliegen Vangen", "Kaartspel"),
], "W": [
    ("Wari", "een variant van mankala"),
    ("De Weerwolven van Wakkerdam", "Kaartspel"),
    ("Wie is het?", "Bordspel"),
    ("Wizard", "Kaartspel"),
], "Y": [
    ("Yahtzee", "Dobbelspel"),
    ("Yoté", "Bordspel"),
    ("Yu-Gi-Oh!", "Kaartspel"),
], "Z": [
    ("Zaklopen", "Straat- en pleinspel"),
    ("Zatre", "Bordspel"),
    ("Zeeslag", "Bordspel"),
    ("Zombies", "Bordspel"),
    ("Zwikken", "Kaartspel"),
]}


def pretty_print():
    for key in GAMES.keys():
        print("{}\n== {}\n{}".format("=" * 80, key.upper(), "=" * 80))
        for game, type in GAMES[key]:
            print("{:50} - {}".format(game, type))


if __name__ == '__main__':
    pretty_print()
